version: '3.8'

services:
  appolo-ldap:
    image: osixia/openldap:1.1.8
    container_name: appolo_ldap
    environment:
      - LDAP_ORGANISATION=Software Architecture
      - LDAP_DOMAIN=arqsoft.unal.edu.co
      - LDAP_BASE_DN=dc=arqsoft,dc=unal,dc=edu,dc=co
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_CONFIG_PASSWORD=config
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d

  db:
    image: postgres:latest
    container_name: auth_ms_db
    environment:
      POSTGRES_DB: apollo_api_development
      POSTGRES_USER: naimu
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      SECRET_KEY_BASE: b5fd37d1625555cc045316c41551d68ad20b8c59107d45bd1fc3654aba6dd7eb186a2b20cba71236f659aa2afc0e77e54e36f46d0d3a2f36d8d0e187c063ac8d
      DATABASE_HOST: db
      DATABASE_USER: naimu
      DATABASE_PASSWORD: password
    depends_on:
      - db
      - appolo-ldap

volumes:
  ldap_data:
  ldap_config:
  db_data:
  postgres_data:
