default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: apollo_api_development
  username: naimu
  password: password
  host: auth_ms_db #remember to change this to from db when executing the API GATEWAY

test:
  <<: *default
  database: apollo_api_test

production:
  <<: *default
  database: apollo_api_production
  username: apollo_api
  password: <%= ENV["APOLLO_API_DATABASE_PASSWORD"] %>
  host: db
